logging:
  level:
    org.mariadb.jdbc: WARN
    root: INFO

spring:
  datasource:
    url: "jdbc:mariadb://fake:3306/PlexDeleter"
    username: ""
    password: ""
    hikari:
      maximum-pool-size: 3
      connectionTimeout: 180000
  flyway:
    baseline-on-migrate: true
    url: "jdbc:mariadb://fake:3306/PlexDeleter"
    user: ""
    password: ""
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: "rabbitmq"
    username: "plexdeleter"
    password: "password"
  mail:
    host: "smtp.host"
    port: 587
    username: "username"
    password: "password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    basename: lang/messages
    use-code-as-default-message: true
  mvc:
    static-path-pattern: "/static/**"
  threads:
    virtual:
      enabled: true
  web:
    resources:
      static-locations: "classpath:/static/"
  session:
    store-type: jdbc
    timeout: 12h
    cookie:
      max-age: 12h
      http-only: true
      same-site: lax
    jdbc:
      initialize-schema: never

server:
  port: 8080
  forward-headers-strategy: native

management:
  endpoint:
    health:
      access: read_only
    info:
      access: read_only
  endpoints:
    access:
      default: read_only
    web:
      exposure:
        include: "health,info"

app:
  exclude-tag: "no-deleter"
  server:
    applicationUrl: "http://app.url"
    web-auth-n:
      relaying-party-name: "PlexDeleter"
      relaying-party-id: "app.url"
      allowed-origins:
        - "http://app.url"
  amqp:
    prefix: "plexdeleter"
    requeueDelay: "PT3H"
  plex:
    endpoint: "https://plex.tv"
    app-endpoint: "https://app.plex.tv"
    communityEndpoint: "https://community.plex.tv/api"
    communityToken: "token"
    pms-endpoint: "http://127.0.0.1:32400"
    pms-token: "token"
    server-id: "server-id"
  tvdb:
    endpoint: "https://api4.thetvdb.com"
    api-key: "api-key"
  tmdb:
    endpoint: "https://api.themoviedb.org"
    token: "token"
  overseerr:
    endpoint: "https://overseerr"
    api-key: "api-key"
  tautulli:
    endpoint: "https://tautulli"
    api-key: "api-key"
  radarr:
    endpoint: "https://radarr"
    api-key: "api-key"
  sonarr:
    endpoint: "https://sonarr"
    api-key: "api-key"
  deletion:
    days-delay: 5
    dry-delete: false
    remote-path-mappings: { }
  notify-watchlist:
    daysDelay: 7
  mail:
    from-address: "from@sender.com"
    from-name: "Plex Watcher"
  supervision:
    webhook-url: "https://webhook"

