[versions]
jetbrains-annotations-version = "24.1.0"

names-version = "0.51.0"
sptringboot-version = "3.3.2"
sptringboot-dm-version = "1.1.6"
graalvm-version = "0.10.2"

[libraries]
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }

[plugins]
sptringboot = { id = "org.springframework.boot", version.ref = "sptringboot-version" }
sptringbootDependencyManagement = { id = "io.spring.dependency-management", version.ref = "sptringboot-dm-version" }
graalvm = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-version" }
names = { id = "com.github.ben-manes.versions", version.ref = "names-version" }
