[versions]
jetbrains-annotations-version = "26.0.2"

sptringboot-version = "3.4.5"
sptringboot-dm-version = "1.1.7"
graalvm-version = "0.10.6"
logback-ecs-version = "1.7.0"

[libraries]
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }
logbackEcs = { group = "co.elastic.logging", name = "logback-ecs-encoder", version.ref = "logback-ecs-version" }

[plugins]
sptringboot = { id = "org.springframework.boot", version.ref = "sptringboot-version" }
sptringbootDependencyManagement = { id = "io.spring.dependency-management", version.ref = "sptringboot-dm-version" }
graalvm = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-version" }
