name: Build

on:
  push:
  workflow_dispatch:

jobs:
  check:
    uses: Rakambda/rakambda-github-workflows/.github/workflows/python-build.yml@main
    with:
      source-folder: src
      
  deploy:
    uses: Rakambda/rakambda-github-workflows/.github/workflows/docker-publish.yml@main
    needs: check
    if: github.ref == ${{ github.event.repository.default_branch }}
    with:
      docker-image: ${{ vars.DOCKER_IMAGE }}
    secrets:
      docker-repo: ${{ secrets.DOCKER_REPO }}
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN }}
